site_name: Vaughan Royce Kildaire

theme:
  name: material
  icon:
    logo: fontawesome/solid/flask

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Academic record: academics.md
  - Education: education.md
  - Personal projects:
      - Index: projects/
      - Lye concentration: projects/lye_concentration
  - About me: about.md
  - Contact: contact.md