site_name: Vaughan Royce Kildaire

theme:
  name: material
  icon:
    logo: fontawesome/solid/flask
  palette:
    scheme: slate
  custom_dir: docs/.overrides # remove local icons if it is not working.
  font: false # add custom font.


extra_css:
- assets/stylesheets/extra_style.css


copyright: <img style="float:left;gap;margin-left:20px" src="/signature_w.png" width=200></img><p style="position:absolute;bottom:0px;right:50px;text-align:right;"> website credit: T.B. Kildaire</p>

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Strategy: Use an absolute path
  - pymdownx.pathconverter:
      base_path: 'YOUR_REPO_NAME' # default: ''
      relative_path: '' # default ''
      absolute: false # default: false
      tags: 'a script img link object embed'



extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - HowTo:
    - Embedding a PDF file: howto/embedding_pdf.md
  - Academic record: academics.md
  - Education: education.md
  - Experience: experience.md
  - Personal projects:
      - Index: projects/index.md
      - Lye concentration: projects/lye_concentration.md
      - HCl vs NaOH Titration: projects/titration_1.md
  - About me: about.md
  - Gallery: media/Gallery/index.md
  - Contact: contact.md
